name: Pre Release

on:
  push:
    branches: [ master ]

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: set up dependencies
        run: |
          sudo apt install libwayland-server0
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease
        env:
          PASSWORD: "${{ secrets.PASSWORD }}"

      - name: Release Package
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: nightly
          prerelease: true
          files: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/apk/release/output-metadata.json